#Site setting
title : 기억을 걷는 시간
description: 'Note of Memory'
url:"https://rrksns.github.io"
author:
  name:"Seol Lee"

#Build settings
markdown: kramdown
highlighter: rouge
logo: false
paginate: 10
baseurl: /
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
